import streamlit as st
import pandas as pd

# Dados de preparação para soldagem
pre_soldagem_dict_completo = pd.DataFrame(
    {
        "Diâmetro Nominal": [
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '2"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '3"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '4"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '5"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '6"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '8"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '10"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '12"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '14"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '16"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '18"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '20"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
            '24"',
        ],
        "Etapas": [
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Cortar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Biselar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
            "Acoplar",
        ],
        "SCH": [
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
            "SCH 40",
            "SCH 40S",
            "SCH 10S",
            "SCH 5S",
            "SCH 80",
            "SCH 80S",
            "SCH 160",
        ],
        "Carbono (min)": [
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            40,
            25,
            25,
            25,
            25,
            30,
            30,
            40,
            30,
            30,
            30,
            30,
            35,
            35,
            45,
            40,
            40,
            40,
            40,
            40,
            40,
            60,
            30,
            30,
            30,
            30,
            35,
            35,
            40,
            30,
            30,
            30,
            30,
            35,
            35,
            45,
            40,
            40,
            40,
            40,
            40,
            40,
            60,
            30,
            30,
            30,
            30,
            40,
            40,
            50,
            35,
            35,
            35,
            35,
            45,
            45,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            75,
        ],
        "Inox (min)": [
            5,
            5,
            5,
            5,
            5,
            5,
            0,
            5,
            5,
            5,
            5,
            5,
            5,
            0,
            10,
            10,
            10,
            10,
            10,
            10,
            0,
            5,
            5,
            5,
            5,
            5,
            5,
            0,
            5,
            5,
            5,
            5,
            5,
            5,
            0,
            10,
            10,
            10,
            10,
            10,
            10,
            0,
            5,
            5,
            5,
            5,
            10,
            10,
            0,
            5,
            5,
            5,
            5,
            10,
            10,
            0,
            15,
            15,
            15,
            15,
            15,
            15,
            0,
            5,
            5,
            5,
            5,
            10,
            10,
            0,
            5,
            5,
            5,
            5,
            10,
            10,
            0,
            15,
            15,
            15,
            15,
            15,
            15,
            0,
            10,
            10,
            10,
            10,
            15,
            15,
            0,
            10,
            10,
            10,
            10,
            15,
            15,
            0,
            20,
            20,
            20,
            20,
            20,
            20,
            0,
            10,
            10,
            10,
            10,
            15,
            15,
            0,
            10,
            10,
            10,
            10,
            15,
            15,
            0,
            20,
            20,
            20,
            20,
            20,
            20,
            0,
            15,
            15,
            15,
            15,
            15,
            15,
            0,
            15,
            15,
            15,
            15,
            20,
            20,
            0,
            20,
            20,
            20,
            20,
            20,
            20,
            0,
            15,
            15,
            15,
            15,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            20,
            20,
            20,
            0,
            0,
            0,
            15,
            15,
            15,
            15,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            20,
            20,
            20,
            0,
            0,
            0,
            20,
            20,
            20,
            20,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            20,
            20,
            20,
            0,
            0,
            0,
            25,
            25,
            25,
            25,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            40,
            40,
            40,
            40,
            0,
            0,
            0,
            30,
            30,
            30,
            30,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            40,
            40,
            40,
            40,
            0,
            0,
            0,
            30,
            30,
            30,
            30,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            60,
            60,
            60,
            60,
            0,
            0,
            0,
        ],
        "Aço Liga (min)": [
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            5,
            5,
            5,
            5,
            5,
            5,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            5,
            5,
            5,
            5,
            10,
            10,
            15,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            10,
            10,
            10,
            10,
            15,
            15,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            15,
            15,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            15,
            15,
            15,
            15,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            20,
            20,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            30,
            20,
            20,
            20,
            20,
            25,
            25,
            40,
            25,
            25,
            25,
            25,
            30,
            30,
            40,
            30,
            30,
            30,
            30,
            35,
            35,
            45,
            40,
            40,
            40,
            40,
            40,
            40,
            60,
            30,
            30,
            30,
            30,
            35,
            35,
            40,
            30,
            30,
            30,
            30,
            35,
            35,
            45,
            40,
            40,
            40,
            40,
            40,
            40,
            60,
            30,
            30,
            30,
            30,
            40,
            40,
            50,
            35,
            35,
            35,
            35,
            45,
            45,
            60,
            60,
            60,
            60,
            60,
            60,
            60,
            75,
        ],
    }
)


def show_pre_soldagem_form():
    st.subheader("Formulário: Preparação para Soldagem")

    # Etapas - Seleção Distinta
    etapa = st.selectbox("Etapas:", pre_soldagem_dict_completo["Etapas"].unique())

    # Filtrar os diâmetros disponíveis com base na etapa selecionada
    diametros_disponiveis = pre_soldagem_dict_completo[
        pre_soldagem_dict_completo["Etapas"] == etapa
    ]["Diâmetro Nominal"].unique()
    diametro = st.selectbox("Diâmetro Nominal:", diametros_disponiveis)

    # Filtrar os valores de SCH disponíveis com base no diâmetro e etapa selecionados
    sch_disponiveis = pre_soldagem_dict_completo[
        (pre_soldagem_dict_completo["Etapas"] == etapa)
        & (pre_soldagem_dict_completo["Diâmetro Nominal"] == diametro)
    ]["SCH"].unique()
    sch = st.selectbox("SCH:", sch_disponiveis)

    # Buscar os detalhes com base nas seleções
    soldagem_selecionada = pre_soldagem_dict_completo[
        (pre_soldagem_dict_completo["Etapas"] == etapa)
        & (pre_soldagem_dict_completo["Diâmetro Nominal"] == diametro)
        & (pre_soldagem_dict_completo["SCH"] == sch)
    ].iloc[0]

    # Mostrar os tempos conforme a seleção
    st.text(f"Tempo Carbono (min): {soldagem_selecionada['Carbono (min)']}")
    st.text(f"Tempo Inox (min): {soldagem_selecionada['Inox (min)']}")
    st.text(f"Tempo Aço Liga (min): {soldagem_selecionada['Aço Liga (min)']}")

    # Campo para inserir quantidade de tubos
    qtd_tubos = st.number_input("Qtde de Tubos:", min_value=1)

    # Calcular Tempo Estimado
    if st.button("Calcular"):
        # Calcular o tempo estimado com base na quantidade de tubos e no tempo de execução
        tempo_estimado = qtd_tubos * soldagem_selecionada["Carbono (min)"]
        st.success(f"Tempo Estimado: {round(tempo_estimado, 2)} minutos")


# Função principal que chama o formulário
def main():
    show_pre_soldagem_form()


if __name__ == "__main__":
    main()
